<project>

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.glisterbyte</groupId>
        <artifactId>mysingingmonsters</artifactId>
        <version>0.1.0</version>
    </parent>

    <artifactId>mysingingmonsters-client-tools</artifactId>

    <properties>
        <maven.deploy.skip>false</maven.deploy.skip>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.glisterbyte</groupId>
            <artifactId>mysingingmonsters-client</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>io.github.cdimascio</groupId>
            <artifactId>java-dotenv</artifactId>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.5.18</version>
        </dependency>
        <dependency>
            <groupId>com.github.therapi</groupId>
            <artifactId>therapi-runtime-javadoc</artifactId>
            <version>0.15.0</version>
        </dependency>
    </dependencies>

</project>